version: 2.1

orbs:
  python: circleci/python@1.2

workflows:
  backup-notion:
    jobs:
      - export-workspace:
          branch_build: master
          filters:
            branches:
              only: feautre/circleci
      - publish-github-release:
          requires:
            - export-workspace

jobs:
  export-workspace:
    parameters:
      branch_build:
        type: string
        default: master
    working_directory: ~/project-export
    docker:
      - image: cimg/python:3.8
    steps:
      - attach_workspace:
          at: ~/project-export
      - checkout
      - run:
          name: Python pip install
          command: |
            pip install requests
            pip install python-slugify
      - run:
          name: Run action
          command: |
            PYTHONPATH=./ python main.py \
                --action "all" \
                --output "build/exported"
      - run:
          name: Dump outputs
          command: |
            echo "Collect exported zip files:\n"
            pwd && ls -l && ls -l ~/project-export/build/exported
            echo "\n---\n"
            if [ -d '~/project-export/build/archives' ]; then
                rm -rf ~/project-export/build/archives
            fi
            mkdir ~/project-export/build/archives
            find ~/project-export/build/exported -name "*.zip" -type f | xargs -I '{}' mv '{}' ~/project-export/build/archives
      - persist_to_workspace:
          root: ~/project-export
          paths:
            - ./build/archives
      - run:
          name: Push to dist
          command: |
#            if [ -d 'dist' ]; then
#                rm -rf dist
#            fi
#            mkdir dist
#            # unzip
#            echo "Unzip files:\n"
#            pwd && ls -l && ls -l ~/project-export/build
#            echo "\n---\n"
#            echo "$(find ~/project-export/build -name "*.zip" -type f | head -1)"

  publish-github-release:
    parameters:
      branch_build:
        type: string
        default: master
    working_directory: ~/project-github-release
    docker:
      - image: cibuilds/github:0.13
    steps:
      - attach_workspace:
          at: ~/project-export
      - run:
          name: "Publish Release on GitHub"
          command: |
            pwd && ls -l && ls -l ~/project-export/build
            VERSION=$(date '+%Y-%m-%d')
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ~/project-export/build
     