version: 2.1

orbs:
  python: circleci/python@1.2

workflows:
  backup-notion:
    jobs:
      - export-workspace:
          branch_build: master
          filters:
            branches:
              only: feautre/circleci
      - publish-github-release:
          requires:
            - export-workspace

jobs:
  export-workspace:
    parameters:
      branch_build:
        type: string
        default: master
    working_directory: ~/project-export
    docker:
      - image: cimg/python:3.8
    steps:
      - attach_workspace:
          at: ~/project-export
      - checkout
      - run:
          name: Python pip install
          command: |
            pip install requests
            pip install python-slugify
      - run:
          name: Run action
          command: |
            PYTHONPATH=./ python main.py \
                --action "export" \
                --output "build"
      - run:
          name: Dump outputs
          command: |
            echo "Exported zip file:\n"
            pwd && ls -l && ls -l ~/project-export/build
            echo "\n---\n"
            echo "$(find ~/project-export/build -name "*.zip" -type f | head -1)"
      - persist_to_workspace:
          root: ~/project-export
          paths:
            - ./build

  publish-github-release:
    parameters:
      branch_build:
        type: string
        default: master
    working_directory: ~/project-github-release
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ~/project-export
      - run:
          name: "Publish Release on GitHub"
          command: |
            pwd && ls -l
            ls -l ~/project-export/build
            mkdir ./archive
            cp -rf ~/project-export/build ./archive
            ls -l ./archive
            ls -l ./archive/build
            ls -l ./archive/build/kaede-akatsuki-090c44bd-574d-460a-b3c9-f932f212046b-zip
            # cd ~/project-export && pwd && ls -l
            VERSION=$(date '+%Y-%m-%d')
            cmd="ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./archive/build/kaede-akatsuki-090c44bd-574d-460a-b3c9-f932f212046b-zip"
            echo "exe: $cmd"
            $("$cmd")